    const products = [
      // CPVC Page 1
      { id: 'cpvc_1', name: 'CPVC Pipe', category: 'CPVC', size: '3/4"', cost: 181, selling: 200, unit: 'Pcs', brand: 'Aparna Standard' },
      { id: 'cpvc_2', name: 'CPVC Socket', category: 'CPVC', size: '3/4"', cost: 8.5, selling: 15, unit: 'Pcs', brand: '' },
      { id: 'cpvc_3', name: 'CPVC Elbow', category: 'CPVC', size: '3/4"', cost: 12.5, selling: 20, unit: 'Pcs', brand: '' },
      { id: 'cpvc_4', name: 'CPVC Tee', category: 'CPVC', size: '3/4"', cost: 19, selling: 25, unit: 'Pcs', brand: '' },
      { id: 'cpvc_5', name: 'CPVC Step Over Bend', category: 'CPVC', size: '3/4"', cost: 65, selling: 75, unit: 'Pcs', brand: '' },
      { id: 'cpvc_6', name: 'CPVC Brass Tee', category: 'CPVC', size: '3/4" x 1/2"', cost: 56.5, selling: 66, unit: 'Pcs', brand: 'Brass' },
      { id: 'cpvc_7', name: 'CPVC Brass Elbow', category: 'CPVC', size: '3/4" x 1/2"', cost: 50, selling: 60, unit: 'Pcs', brand: 'Brass' },
      { id: 'cpvc_8', name: 'CPVC Brass FTA', category: 'CPVC', size: '3/4" x 1/2"', cost: 50, selling: 60, unit: 'Pcs', brand: 'Brass' },
      { id: 'cpvc_9', name: 'CPVC Brass MTA', category: 'CPVC', size: '3/4" x 1/2"', cost: 71.5, selling: 80, unit: 'Pcs', brand: 'Brass' },
      { id: 'cpvc_10', name: 'CPVC Bush', category: 'CPVC', size: '3/4"', cost: 11, selling: 15, unit: 'Pcs', brand: '' },
      { id: 'cpvc_11', name: 'CPVC End Cap', category: 'CPVC', size: '3/4"', cost: 9, selling: 12, unit: 'Pcs', brand: '' },
      { id: 'cpvc_12', name: 'CPVC Brass Mixer Adaptor', category: 'CPVC', size: '3/4"', cost: 275, selling: 300, unit: 'Pcs', brand: 'Brass' },
      { id: 'cpvc_13', name: 'CPVC Shoe Elbow', category: 'CPVC', size: '3/4"', cost: 15, selling: 20, unit: 'Pcs', brand: '' },
      { id: 'cpvc_14', name: 'CPVC Solvent (100ml)', category: 'CPVC', size: '100 ml', cost: 130, selling: 140, unit: 'Can', brand: 'Heavy' },
      { id: 'cpvc_15', name: 'CPVC Solvent (50ml)', category: 'CPVC', size: '50 ml', cost: 85, selling: 90, unit: 'Can', brand: 'Heavy' },

      // UPVC Page 1
      { id: 'upvc_1', name: 'UPVC Pipe (1 inchi pipe)', category: 'UPVC', size: '1"', cost: 199, selling: 230, unit: 'Pcs', brand: 'A-Class' },
      { id: 'upvc_2', name: 'UPVC Socket', category: 'UPVC', size: '1"', cost: 13, selling: 20, unit: 'Pcs', brand: '' },
      { id: 'upvc_3', name: 'UPVC Elbow', category: 'UPVC', size: '1"', cost: 19, selling: 25, unit: 'Pcs', brand: '' },
      { id: 'upvc_4', name: 'UPVC Tee', category: 'UPVC', size: '1"', cost: 25, selling: 30, unit: 'Pcs', brand: '' },
      { id: 'upvc_5', name: 'UPVC Shoe Elbow', category: 'UPVC', size: '1"', cost: 18, selling: 25, unit: 'Pcs', brand: '' },
      { id: 'upvc_6', name: 'UPVC Brass Elbow', category: 'UPVC', size: '1" x 1/2"', cost: 66.5, selling: 75, unit: 'Pcs', brand: 'Brass' },
      { id: 'upvc_7', name: 'UPVC Brass Tee', category: 'UPVC', size: '1" x 1/2"', cost: 77, selling: 85, unit: 'Pcs', brand: 'Brass' },
      { id: 'upvc_8', name: 'UPVC FTA', category: 'UPVC', size: '1"', cost: 14, selling: 20, unit: 'Pcs', brand: '' },
      { id: 'upvc_9', name: 'UPVC MTA', category: 'UPVC', size: '1"', cost: 11, selling: 15, unit: 'Pcs', brand: '' },
      { id: 'upvc_10', name: 'UPVC Tank Nipple', category: 'UPVC', size: '1"', cost: 35.5, selling: 50, unit: 'Pcs', brand: '' },
      { id: 'upvc_11', name: 'UPVC Union', category: 'UPVC', size: '1"', cost: 36.5, selling: 45, unit: 'Pcs', brand: '' },
      { id: 'upvc_12', name: 'UPVC Ball Valve', category: 'UPVC', size: '1"', cost: 95.5, selling: 110, unit: 'Pcs', brand: '' },
      { id: 'upvc_13', name: 'UPVC Clamp', category: 'UPVC', size: '1"', cost: 4.5, selling: 10, unit: 'Pcs', brand: '' },
      { id: 'upvc_14', name: 'UPVC End Cap', category: 'UPVC', size: '1"', cost: 9.5, selling: 15, unit: 'Pcs', brand: '' },
      { id: 'upvc_15', name: 'UPVC Bush', category: 'UPVC', size: '1" x 3/4"', cost: 6.5, selling: 10, unit: 'Pcs', brand: '' },
      { id: 'upvc_16', name: 'UPVC Bush', category: 'UPVC', size: '1" x 1/2"', cost: 6.5, selling: 10, unit: 'Pcs', brand: '' },
      { id: 'upvc_17', name: 'UPVC Pipe (1.25 inchi)', category: 'UPVC', size: '1 1/4"', cost: 225, selling: 260, unit: 'Pcs', brand: '' },
      { id: 'upvc_18', name: 'UPVC Socket', category: 'UPVC', size: '1 1/4"', cost: 20, selling: 30, unit: 'Pcs', brand: '' },
      { id: 'upvc_19', name: 'UPVC Elbow', category: 'UPVC', size: '1 1/4"', cost: 31, selling: 40, unit: 'Pcs', brand: '' },
      { id: 'upvc_20', name: 'UPVC Tee', category: 'UPVC', size: '1 1/4"', cost: 40.5, selling: 45, unit: 'Pcs', brand: '' },
      { id: 'upvc_21', name: 'UPVC Shoe Elbow', category: 'UPVC', size: '1 1/4"', cost: 42, selling: 50, unit: 'Pcs', brand: '' },
      { id: 'upvc_22', name: 'UPVC Tank Connector', category: 'UPVC', size: '1 1/4"', cost: 64, selling: 75, unit: 'Pcs', brand: '' },
      { id: 'upvc_23', name: 'UPVC Union', category: 'UPVC', size: '1 1/4"', cost: 50.5, selling: 60, unit: 'Pcs', brand: '' },
      { id: 'upvc_24', name: 'UPVC Ball Valve', category: 'UPVC', size: '1 1/4"', cost: 150, selling: 160, unit: 'Pcs', brand: '' },
      { id: 'upvc_25', name: 'UPVC Bush', category: 'UPVC', size: '1 1/4" x 1"', cost: 12.5, selling: 20, unit: 'Pcs', brand: '' },
      { id: 'upvc_26', name: 'UPVC End Cap', category: 'UPVC', size: '1 1/4" x 1"', cost: 12.5, selling: 20, unit: 'Pcs', brand: '' },
      { id: 'upvc_27', name: 'UPVC FTA', category: 'UPVC', size: '3/4"', cost: 7.5, selling: 10, unit: 'Pcs', brand: '' },

      { id: 'pvc_1', name: 'PVC Pipe', category: 'PVC', size: '3/4"', cost: 138, selling: 160, unit: 'Pcs', brand: '' },
      { id: 'pvc_2', name: 'PVC Elbow', category: 'PVC', size: '3/4"', cost: 12.5, selling: 20, unit: 'Pcs', brand: '' },
      { id: 'pvc_3', name: 'PVC Socket', category: 'PVC', size: '3/4"', cost: 8, selling: 15, unit: 'Pcs', brand: '' },
      { id: 'pvc_4', name: 'PVC Tee', category: 'PVC', size: '3/4"', cost: 16.5, selling: 20, unit: 'Pcs', brand: '' },
      { id: 'pvc_5', name: 'PVC Shoe Elbow', category: 'PVC', size: '3/4"', cost: 10.5, selling: 15, unit: 'Pcs', brand: '' },
      { id: 'pvc_6', name: 'PVC Brass Elbow', category: 'PVC', size: '3/4" x 1/2"', cost: 55, selling: 60, unit: 'Pcs', brand: '' },
      { id: 'pvc_7', name: 'PVC Brass Tee', category: 'PVC', size: '3/4" x 1/2"', cost: 62.5, selling: 70, unit: 'Pcs', brand: '' },
      { id: 'pvc_8', name: 'PVC Tank Nipple', category: 'PVC', size: '3/4"', cost: 27, selling: 40, unit: 'Pcs', brand: '' },
      { id: 'pvc_9', name: 'PVC Union', category: 'PVC', size: '3/4"', cost: 25, selling: 35, unit: 'Pcs', brand: '' },
      { id: 'pvc_10', name: 'PVC Ball Valve', category: 'PVC', size: '3/4"', cost: 72, selling: 85, unit: 'Pcs', brand: '' },
      { id: 'pvc_11', name: 'PVC End Cap', category: 'PVC', size: '3/4"', cost: 6.5, selling: 10, unit: 'Pcs', brand: '' },
      { id: 'pvc_12', name: 'PVC Clamp', category: 'PVC', size: '3/4"', cost: 4, selling: 10, unit: 'Pcs', brand: '' },
      { id: 'pvc_13', name: 'PVC Pipe (1/2 inchi pipe)', category: 'PVC', size: '1/2"', cost: 102.5, selling: 120, unit: 'Pcs', brand: '' },
      { id: 'pvc_14', name: 'PVC Elbow', category: 'PVC', size: '1/2"', cost: 7, selling: 10, unit: 'Pcs', brand: '' },
      { id: 'pvc_15', name: 'PVC Socket', category: 'PVC', size: '1/2"', cost: 5, selling: 10, unit: 'Pcs', brand: '' },
      { id: 'pvc_16', name: 'PVC Tee', category: 'PVC', size: '1/2"', cost: 9, selling: 15, unit: 'Pcs', brand: '' },
      { id: 'pvc_17', name: 'PVC Brass Elbow', category: 'PVC', size: '1/2"', cost: 50, selling: 60, unit: 'Pcs', brand: '' },
      { id: 'pvc_18', name: 'PVC Brass Tee', category: 'PVC', size: '1/2"', cost: 58, selling: 65, unit: 'Pcs', brand: '' },
      { id: 'pvc_19', name: 'PVC FTA', category: 'PVC', size: '1/2"', cost: 6, selling: 10, unit: 'Pcs', brand: '' },
      { id: 'pvc_20', name: 'PVC MTA', category: 'PVC', size: '1/2"', cost: 6, selling: 10, unit: 'Pcs', brand: '' },
      { id: 'pvc_21', name: 'PVC Brass FTA', category: 'PVC', size: '1/2"', cost: 44, selling: 55, unit: 'Pcs', brand: '' },
      { id: 'pvc_22', name: 'PVC Brass MTA', category: 'PVC', size: '1/2"', cost: 59, selling: 65, unit: 'Pcs', brand: '' },
      { id: 'pvc_23', name: 'PVC Clamp', category: 'PVC', size: '1/2"', cost: 3.5, selling: 10, unit: 'Pcs', brand: '' },
      { id: 'pvc_24', name: 'PVC End Cap', category: 'PVC', size: '1/2"', cost: 4.5, selling: 10, unit: 'Pcs', brand: '' },
      { id: 'pvc_25', name: 'PVC Solvent (100ml)', category: 'PVC', size: '100 ml', cost: 105, selling: 120, unit: 'Can', brand: '' },
      { id: 'pvc_26', name: 'PVC Solvent (50ml)', category: 'PVC', size: '50 ml', cost: 70, selling: 90, unit: 'Can', brand: '' },
      { id: 'pvc_27', name: 'Chiri Nail', category: 'HARDWARE', size: '1"', cost: 110, selling: 125, unit: 'Packet', brand: '' },
      { id: 'pvc_28', name: 'Chiri Nail', category: 'HARDWARE', size: '1 1/2"', cost: 110, selling: 125, unit: 'Packet', brand: '' },
      { id: 'pvc_29', name: 'Black Nail (Kanta)', category: 'HARDWARE', size: '2"', cost: 240, selling: 260, unit: 'Packet', brand: '' },
      { id: 'pvc_30', name: 'Teflon Tape', category: 'HARDWARE', size: 'Standard', cost: 7.5, selling: 10, unit: 'Pcs', brand: '' },
      { id: 'pvc_31', name: 'Hex Blade', category: 'HARDWARE', size: 'Standard', cost: 10, selling: 15, unit: 'Pcs', brand: '' },

      // Drainage / SWR PVC (4" and 3")
      { id: 'swr_1', name: '4" 10\' S/S Drainage Pipe', category: 'PVC', size: '4" x 10ft', cost: 400, selling: 450, unit: 'Pcs', brand: 'S/S' },
      { id: 'swr_2', name: '4" D/S Drainage Pipe', category: 'PVC', size: '4"', cost: 493.5, selling: 550, unit: 'Pcs', brand: 'D/S' },
      { id: 'swr_3', name: '4" SWR Socket', category: 'PVC', size: '4"', cost: 52, selling: 60, unit: 'Pcs', brand: '' },
      { id: 'swr_4', name: '4" Plain Tee', category: 'PVC', size: '4"', cost: 133, selling: 150, unit: 'Pcs', brand: '' },
      { id: 'swr_5', name: '4" Door Bend', category: 'PVC', size: '4"', cost: 120, selling: 135, unit: 'Pcs', brand: '' },
      { id: 'swr_6', name: '4" P-Trap (4 inchi p trap)', category: 'PVC', size: '4"', cost: 208, selling: 230, unit: 'Pcs', brand: 'P-Trap' },
      { id: 'swr_7', name: 'Nahani Trap (N-Trap)', category: 'PVC', size: '4" x 3"', cost: 91, selling: 100, unit: 'Pcs', brand: '' },
      { id: 'swr_8', name: '4" Plain Y', category: 'PVC', size: '4"', cost: 191, selling: 210, unit: 'Pcs', brand: '' },
      { id: 'swr_9', name: '4" End Cap', category: 'PVC', size: '4"', cost: 30.5, selling: 35, unit: 'Pcs', brand: '' },
      { id: 'swr_10', name: '4" Cowel (Vent)', category: 'PVC', size: '4"', cost: 20, selling: 30, unit: 'Pcs', brand: '' },
      { id: 'swr_11', name: '4" Clamp', category: 'PVC', size: '4"', cost: 15, selling: 20, unit: 'Pcs', brand: '' },
      { id: 'swr_12', name: '3" 10\' S/S Pipe', category: 'PVC', size: '3" x 10ft', cost: 240, selling: 270, unit: 'Pcs', brand: '' },
      { id: 'swr_13', name: '3" D/S Pipe', category: 'PVC', size: '3"', cost: 265, selling: 295, unit: 'Pcs', brand: '' },
      { id: 'swr_14', name: '3" Plain Bend', category: 'PVC', size: '3"', cost: 52, selling: 60, unit: 'Pcs', brand: '' },
      { id: 'swr_15', name: '3" Plain Tee', category: 'PVC', size: '3"', cost: 75, selling: 85, unit: 'Pcs', brand: '' },
      { id: 'swr_16', name: '3" Socket', category: 'PVC', size: '3"', cost: 44.5, selling: 55, unit: 'Pcs', brand: '' },
      { id: 'swr_17', name: '3" Door Bend', category: 'PVC', size: '3"', cost: 66.5, selling: 75, unit: 'Pcs', brand: '' },
      { id: 'swr_18', name: '3" Door Tee', category: 'PVC', size: '3"', cost: 90, selling: 100, unit: 'Pcs', brand: '' },
      { id: 'swr_19', name: '3" Plain Y', category: 'PVC', size: '3"', cost: 98, selling: 110, unit: 'Pcs', brand: '' },
      { id: 'swr_20', name: '3" Cowel (Vent)', category: 'PVC', size: '3"', cost: 17, selling: 20, unit: 'Pcs', brand: '' },
      { id: 'swr_21', name: '3" End Cap', category: 'PVC', size: '3"', cost: 20, selling: 25, unit: 'Pcs', brand: '' },
      { id: 'swr_22', name: 'PVC Reducer', category: 'PVC', size: '4" x 3"', cost: 67.5, selling: 75, unit: 'Pcs', brand: '' },
      { id: 'swr_23', name: 'Rubber Lubricant', category: 'PVC', size: '100 gm', cost: 32, selling: 40, unit: 'Pcs', brand: '' },
      { id: 'swr_24', name: 'Dummy Plug', category: 'PVC', size: '1/2"', cost: 2.5, selling: 5, unit: 'Pcs', brand: '' },

      { id: 'cp_1', name: 'Prado Wall Mixer', category: 'CP_FITTINGS', size: 'Standard', cost: 2250, selling: 2500, unit: 'Pcs', brand: 'Prado' },
      { id: 'cp_2', name: 'Prado Bib Cock', category: 'CP_FITTINGS', size: 'Standard', cost: 467.5, selling: 540, unit: 'Pcs', brand: 'Prado' },
      { id: 'cp_3', name: 'Prado Pillar Cock', category: 'CP_FITTINGS', size: 'Standard', cost: 536, selling: 590, unit: 'Pcs', brand: 'Prado' },
      { id: 'cp_4', name: 'Prado Swan Neck', category: 'CP_FITTINGS', size: 'Standard', cost: 756, selling: 820, unit: 'Pcs', brand: 'Prado' },
      { id: 'cp_5', name: 'Prado Sink Cock', category: 'CP_FITTINGS', size: 'Standard', cost: 756, selling: 815, unit: 'Pcs', brand: 'Prado' },
      { id: 'cp_6', name: 'Prado 2 in 1 Bib Cock', category: 'CP_FITTINGS', size: 'Standard', cost: 880, selling: 950, unit: 'Pcs', brand: 'Prado' },
      { id: 'cp_7', name: 'Prado 2 in 1 Angle Cock', category: 'CP_FITTINGS', size: 'Standard', cost: 784, selling: 860, unit: 'Pcs', brand: 'Prado' },
      { id: 'cp_8', name: 'Ford Wall Mixer', category: 'CP_FITTINGS', size: 'Standard', cost: 2035, selling: 2235, unit: 'Pcs', brand: 'Ford' },
      { id: 'cp_9', name: 'Ford Sink Mixer', category: 'CP_FITTINGS', size: 'Standard', cost: 1680, selling: 1848, unit: 'Pcs', brand: 'Ford' },
      { id: 'cp_10', name: 'Ford Bib Cock', category: 'CP_FITTINGS', size: 'Standard', cost: 398.5, selling: 440, unit: 'Pcs', brand: 'Ford' },
      { id: 'cp_11', name: 'Ford Pillar Cock', category: 'CP_FITTINGS', size: 'Standard', cost: 453.75, selling: 500, unit: 'Pcs', brand: 'Ford' },
      { id: 'cp_12', name: 'Ford Swan Neck', category: 'CP_FITTINGS', size: 'Standard', cost: 687.5, selling: 760, unit: 'Pcs', brand: 'Ford' },
      { id: 'cp_13', name: 'Ford Sink Cock', category: 'CP_FITTINGS', size: 'Standard', cost: 660, selling: 726, unit: 'Pcs', brand: 'Ford' },
      { id: 'cp_14', name: 'CSPL Angle Cock', category: 'CP_FITTINGS', size: 'Standard', cost: 220, selling: 250, unit: 'Pcs', brand: 'CSPL' },
      { id: 'cp_15', name: 'M/S Angle Cock', category: 'CP_FITTINGS', size: 'Standard', cost: 88, selling: 150, unit: 'Pcs', brand: 'M/S' },
      { id: 'cp_16', name: 'ABS Health Faucet Set (H/F)', category: 'CP_FITTINGS', size: 'Set', cost: 210, selling: 250, unit: 'Set', brand: 'ABS' },
      { id: 'cp_17', name: 'Towel Ring', category: 'CP_FITTINGS', size: 'Standard', cost: 125, selling: 150, unit: 'Pcs', brand: '' },
      { id: 'cp_18', name: 'Towel Rod (24 inch)', category: 'CP_FITTINGS', size: '24"', cost: 175, selling: 250, unit: 'Pcs', brand: 'SS' },
      { id: 'cp_19', name: 'Towel Rod (18 inch)', category: 'CP_FITTINGS', size: '18"', cost: 165, selling: 220, unit: 'Pcs', brand: 'SS' },
      { id: 'cp_20', name: 'Soap Dish (SS)', category: 'CP_FITTINGS', size: 'Standard', cost: 95, selling: 115, unit: 'Pcs', brand: 'SS' },
      { id: 'cp_21', name: 'Red Tap', category: 'CP_FITTINGS', size: 'Standard', cost: 55, selling: 70, unit: 'Pcs', brand: '' },
      { id: 'cp_22', name: 'Corner Basin Shelf (U/U)', category: 'SANITARY', size: 'Standard', cost: 270, selling: 290, unit: 'Pcs', brand: '' },
      { id: 'cp_23', name: 'Nozzle Bib Cock', category: 'CP_FITTINGS', size: 'Standard', cost: 48, selling: 60, unit: 'Pcs', brand: '' },
      { id: 'cp_24', name: 'Khunti (Cloth Hooks)', category: 'HARDWARE', size: 'Standard', cost: 78, selling: 85, unit: 'Pcs', brand: 'SS' },
      { id: 'cp_25', name: 'SS Jali Plain 4"', category: 'CP_FITTINGS', size: '4"', cost: 22, selling: 30, unit: 'Pcs', brand: 'SS' },
      { id: 'cp_26', name: 'SS Jali Hole 4"', category: 'CP_FITTINGS', size: '4"', cost: 22, selling: 30, unit: 'Pcs', brand: 'SS' },
      { id: 'cp_27', name: 'Kitchen Sink 24" x 18"', category: 'SANITARY', size: '24" x 18"', cost: 950, selling: 1050, unit: 'Pcs', brand: 'SS 304' },
      { id: 'cp_28', name: 'Kitchen Sink 20" x 17"', category: 'SANITARY', size: '20" x 17"', cost: 920, selling: 1020, unit: 'Pcs', brand: 'SS 304' },
      { id: 'cp_29', name: 'Conti Overhead Shower', category: 'CP_FITTINGS', size: 'Standard', cost: 200, selling: 250, unit: 'Pcs', brand: 'Conti' },
      { id: 'cp_30', name: 'Jaquar Type Shower', category: 'CP_FITTINGS', size: 'Standard', cost: 300, selling: 330, unit: 'Pcs', brand: 'Jaquar Model' },
      { id: 'cp_31', name: 'Polo Bib Cock', category: 'CP_FITTINGS', size: 'Standard', cost: 25, selling: 35, unit: 'Pcs', brand: 'Polo' },
      { id: 'cp_32', name: 'Polo Angle Cock', category: 'CP_FITTINGS', size: 'Standard', cost: 25, selling: 35, unit: 'Pcs', brand: 'Polo' },
      { id: 'cp_33', name: 'Sintex Water Tank 1000L', category: 'SANITARY', size: '1000 Ltr', cost: 4500, selling: 5200, unit: 'Pcs', brand: 'Sintex' },
      { id: 'cp_34', name: 'Sintex Water Tank 500L', category: 'SANITARY', size: '500 Ltr', cost: 2300, selling: 2700, unit: 'Pcs', brand: 'Sintex' },
      { id: 'cp_35', name: 'Garden Pipe VTK', category: 'HARDWARE', size: '1"', cost: 1064, selling: 1250, unit: 'Bundle', brand: 'VTK' },

      { id: 'sp_1', name: 'Spars Pearl Bib Cock TS 101', category: 'CP_FITTINGS', size: 'Standard', cost: 126, selling: 160, unit: 'Pcs', brand: 'Spars Pearl' },
      { id: 'sp_2', name: 'Spars Pearl Angle Cock TS 105', category: 'CP_FITTINGS', size: 'Standard', cost: 126.75, selling: 153, unit: 'Pcs', brand: 'Spars Pearl' },
      { id: 'sp_3', name: 'Extension Nipple', category: 'CP_FITTINGS', size: 'Standard', cost: 33.8, selling: 40, unit: 'Pcs', brand: 'Brass' },
      { id: 'sp_4', name: 'Wall Mixer L Bend', category: 'CP_FITTINGS', size: 'Standard', cost: 981.5, selling: 1180, unit: 'Pcs', brand: 'Spars Pearl' },
      { id: 'sp_5', name: 'Spars Pearl Swan Neck', category: 'CP_FITTINGS', size: 'Standard', cost: 393, selling: 450, unit: 'Pcs', brand: 'Spars Pearl' },
      { id: 'sp_6', name: 'Spars Pearl Sink Cock', category: 'CP_FITTINGS', size: 'Standard', cost: 387, selling: 450, unit: 'Pcs', brand: 'Spars Pearl' },
      { id: 'sp_7', name: 'Spars Pearl Pillar Cock', category: 'CP_FITTINGS', size: 'Standard', cost: 260, selling: 310, unit: 'Pcs', brand: 'Spars Pearl' },
      { id: 'sp_8', name: 'Soap Dispenser', category: 'CP_FITTINGS', size: 'Standard', cost: 377, selling: 414, unit: 'Pcs', brand: 'Spars Pearl' },
      { id: 'sp_9', name: 'Hero HP 1.2 MTR Chrome', category: 'CP_FITTINGS', size: '1.2 Meter', cost: 481, selling: 530, unit: 'Pcs', brand: 'Hero' },
      { id: 'sp_10', name: 'PVC Corner Shelf', category: 'SANITARY', size: 'Standard', cost: 391, selling: 460, unit: 'Pcs', brand: 'PVC' },
      { id: 'sp_11', name: 'Mirror Cabinet', category: 'SANITARY', size: 'Standard', cost: 1066, selling: 1250, unit: 'Pcs', brand: 'Cabinet' },
      { id: 'sp_12', name: 'Flash Cistern (Flush Tank)', category: 'SANITARY', size: 'Standard', cost: 650, selling: 780, unit: 'Pcs', brand: 'Standard' },
      { id: 'sp_13', name: 'Z Spray 1 MTR', category: 'CP_FITTINGS', size: '1 Meter', cost: 406, selling: 486, unit: 'Pcs', brand: 'Z' },
      { id: 'san_1', name: 'Orissa Pan (OT Pan) 20"', category: 'SANITARY', size: '20"', cost: 390, selling: 430, unit: 'Pcs', brand: 'Ceramic' },
      { id: 'san_2', name: 'Orissa Pan (OT Pan) 23"', category: 'SANITARY', size: '23"', cost: 490, selling: 540, unit: 'Pcs', brand: 'Ceramic' },
      { id: 'san_3', name: 'EWC Commode Western', category: 'SANITARY', size: 'Standard', cost: 760, selling: 840, unit: 'Pcs', brand: 'Ceramic' },
      { id: 'san_4', name: 'Wash Basin 18" x 12"', category: 'SANITARY', size: '18" x 12"', cost: 325, selling: 360, unit: 'Pcs', brand: 'Ceramic' },
      { id: 'san_5', name: 'Pedestal Wash Basin Set', category: 'SANITARY', size: 'Standard', cost: 1400, selling: 1540, unit: 'Set', brand: 'Ceramic' },
      { id: 'san_6', name: 'One Piece Designer Commode', category: 'SANITARY', size: 'Standard', cost: 4800, selling: 5280, unit: 'Pcs', brand: 'Ceramic' },

      { id: 'elec_1', name: 'Reliance Motor 1x12 (Oil Cooled)', category: 'SUBMERSIBLE', size: '1 HP (1x12)', cost: 8500, selling: 9350, unit: 'Set', brand: 'Reliance' },
      { id: 'elec_2', name: 'Sunrise Motor 1x14 (Water Cooled)', category: 'SUBMERSIBLE', size: '1 HP (1x14)', cost: 7090, selling: 7790, unit: 'Set', brand: 'Sunrise' },
      { id: 'elec_3', name: 'Sunrise Motor 1.5x19 (Oil Cooled)', category: 'SUBMERSIBLE', size: '1.5 HP (1.5x19)', cost: 10785, selling: 11785, unit: 'Set', brand: 'Sunrise' },
      { id: 'elec_4', name: 'Mahindra Motor 1x10 (Oil Cooled)', category: 'SUBMERSIBLE', size: '1 HP (1x10)', cost: 4400, selling: 4840, unit: 'Set', brand: 'Mahindra' },
      { id: 'elec_5', name: 'Control Panel Starter 1 HP', category: 'SUBMERSIBLE', size: '1 HP', cost: 1350, selling: 1490, unit: 'Pcs', brand: 'Standard' },
      { id: 'elec_6', name: 'Control Panel Starter 1.5 HP', category: 'SUBMERSIBLE', size: '1.5 HP', cost: 1500, selling: 1650, unit: 'Pcs', brand: 'Standard' },
      { id: 'elec_7', name: 'Boring Cap (Dharkan) 6" x 1"', category: 'SUBMERSIBLE', size: '6" x 1"', cost: 185, selling: 200, unit: 'Pcs', brand: 'CI' },
      { id: 'elec_8', name: 'Boring Cap (Dharkan) 6" x 1 1/4"', category: 'SUBMERSIBLE', size: '6" x 1 1/4"', cost: 185, selling: 200, unit: 'Pcs', brand: 'CI' },
      { id: 'elec_9', name: 'Submersible Adaptor', category: 'SUBMERSIBLE', size: '1 1/4" x 1"', cost: 185, selling: 200, unit: 'Pcs', brand: 'CI' },
      { id: 'elec_10', name: 'Column Pipe Submersible 1 1/4"', category: 'SUBMERSIBLE', size: '1 1/4"', cost: 148, selling: 170, unit: 'Pcs', brand: 'Column' },
      { id: 'elec_11', name: 'Column Pipe Submersible 1 1/2"', category: 'SUBMERSIBLE', size: '1 1/2"', cost: 237, selling: 260, unit: 'Pcs', brand: 'Column' },
      { id: 'elec_12', name: 'Crompton Submersible Flat Wire', category: 'ELECTRIC', size: '1.5 sq mm', cost: 34, selling: 40, unit: 'Meter', brand: 'Crompton' },
      { id: 'elec_13', name: 'Crompton Submersible Flat Wire', category: 'ELECTRIC', size: '2.5 sq mm', cost: 50, selling: 60, unit: 'Meter', brand: 'Crompton' },
      { id: 'elec_14', name: 'Starter Panel Local', category: 'ELECTRIC', size: 'Standard', cost: 750, selling: 825, unit: 'Pcs', brand: 'Starter' },

      /* --- GLOSS ENAMEL PAINTS (From Notebook Page 1) --- */
      { id: 'paint_ge_1', name: 'Gloss Enamel White Paint', category: 'PAINT', size: '500 ml', cost: 166.38, selling: 190, unit: 'Dabba', brand: 'Gloss Enamel' },
      { id: 'paint_ge_2', name: 'Gloss Enamel White Paint', category: 'PAINT', size: '1 Litre', cost: 319.78, selling: 360, unit: 'Dabba', brand: 'Gloss Enamel' },
      { id: 'paint_ge_3', name: 'Gloss Enamel Phiroj Blue Paint', category: 'PAINT', size: '500 ml', cost: 158.4, selling: 180, unit: 'Dabba', brand: 'Gloss Enamel' },
      { id: 'paint_ge_4', name: 'Gloss Enamel Phiroj Blue Paint', category: 'PAINT', size: '1 Litre', cost: 295, selling: 350, unit: 'Dabba', brand: 'Gloss Enamel' },

      /* --- PROMISE WHITE BASE INTERIOR (PROMIS W/T BASE INT) --- */
      { id: 'paint_pr_int_1', name: 'Promise Interior White (Promis Int W/T)', category: 'PAINT', size: '1 Litre', cost: 198.24, selling: 230, unit: 'Bucket', brand: 'Promise' },
      { id: 'paint_pr_int_4', name: 'Promise Interior White (Promis Int W/T)', category: 'PAINT', size: '4 Litre', cost: 750.48, selling: 975.6, unit: 'Bucket', brand: 'Promise' },
      { id: 'paint_pr_int_10', name: 'Promise Interior White (Promis Int W/T)', category: 'PAINT', size: '10 Litre', cost: 1781.18, selling: 2215, unit: 'Bucket', brand: 'Promise' },
      { id: 'paint_pr_int_20', name: 'Promise Interior White (Promis Int W/T)', category: 'PAINT', size: '20 Litre', cost: 3444.42, selling: 3944, unit: 'Bucket', brand: 'Promise' },

      /* --- PROMISE EXTERIOR WHITE (PROMIS EXT W/T) --- */
      { id: 'paint_pr_ext_1', name: 'Promise Exterior White (Promis Ext W/T)', category: 'PAINT', size: '1 Litre', cost: 226.56, selling: 250, unit: 'Bucket', brand: 'Promise' },
      { id: 'paint_pr_ext_4', name: 'Promise Exterior White (Promis Ext W/T)', category: 'PAINT', size: '4 Litre', cost: 872.02, selling: 1160, unit: 'Bucket', brand: 'Promise' },
      { id: 'paint_pr_ext_10', name: 'Promise Exterior White (Promis Ext W/T)', category: 'PAINT', size: '10 Litre', cost: 2103, selling: 2700, unit: 'Bucket', brand: 'Promise' },
      { id: 'paint_pr_ext_20', name: 'Promise Exterior White (Promis Ext W/T)', category: 'PAINT', size: '20 Litre', cost: 4084.98, selling: 4500, unit: 'Bucket', brand: 'Promise' },

      /* --- PROMISE SMART CHOICE WHITE INTERIOR (SMART W/T INT) --- */
      { id: 'paint_sm_int_1', name: 'Smart Choice Interior White (Smart W/T Int)', category: 'PAINT', size: '1 Litre', cost: 126.26, selling: 138, unit: 'Bucket', brand: 'Smart Choice' },
      { id: 'paint_sm_int_4', name: 'Smart Choice Interior White (Smart W/T Int)', category: 'PAINT', size: '4 Litre', cost: 480.26, selling: 624.33, unit: 'Bucket', brand: 'Smart Choice' },
      { id: 'paint_sm_int_10', name: 'Smart Choice Interior White (Smart W/T Int)', category: 'PAINT', size: '10 Litre', cost: 1126.9, selling: 1464.97, unit: 'Bucket', brand: 'Smart Choice' },
      { id: 'paint_sm_int_20', name: 'Smart Choice Interior White (Smart W/T Int)', category: 'PAINT', size: '20 Litre', cost: 2165.3, selling: 2814.89, unit: 'Bucket', brand: 'Smart Choice' },

      /* --- PROMISE SMART CHOICE WHITE EXTERIOR (SMART W/T EXT) --- */
      { id: 'paint_sm_ext_1', name: 'Smart Choice Exterior White (Smart W/T Ext)', category: 'PAINT', size: '1 Litre', cost: 160.48, selling: 208.24, unit: 'Bucket', brand: 'Smart Choice' },
      { id: 'paint_sm_ext_4', name: 'Smart Choice Exterior White (Smart W/T Ext)', category: 'PAINT', size: '4 Litre', cost: 611.24, selling: 794.61, unit: 'Bucket', brand: 'Smart Choice' },
      { id: 'paint_sm_ext_10', name: 'Smart Choice Exterior White (Smart W/T Ext)', category: 'PAINT', size: '10 Litre', cost: 1439.6, selling: 1871.48, unit: 'Bucket', brand: 'Smart Choice' },
      { id: 'paint_sm_ext_20', name: 'Smart Choice Exterior White (Smart W/T Ext)', category: 'PAINT', size: '20 Litre', cost: 2596, selling: 3374.8, unit: 'Bucket', brand: 'Smart Choice' },

      /* --- PRIMERS: SMART INT PRIMER (From Notebook Page 2) --- */
      { id: 'paint_prm_smi_1', name: 'Smart Interior Primer', category: 'PAINT', size: '1 Litre', cost: 120, selling: 130, unit: 'Can', brand: 'Smart' },
      { id: 'paint_prm_smi_4', name: 'Smart Interior Primer', category: 'PAINT', size: '4 Litre', cost: 416.54, selling: 510, unit: 'Bucket', brand: 'Smart' },
      { id: 'paint_prm_smi_10', name: 'Smart Interior Primer', category: 'PAINT', size: '10 Litre', cost: 951.08, selling: 1120, unit: 'Bucket', brand: 'Smart' },
      { id: 'paint_prm_smi_20', name: 'Smart Interior Primer', category: 'PAINT', size: '20 Litre', cost: 1638.9, selling: 2100, unit: 'Bucket', brand: 'Smart' },

      /* --- PRIMERS: SMART EXT PRIMER --- */
      { id: 'paint_prm_sme_1', name: 'Smart Exterior Primer', category: 'PAINT', size: '1 Litre', cost: 149.86, selling: 180, unit: 'Can', brand: 'Smart' },
      { id: 'paint_prm_sme_4', name: 'Smart Exterior Primer', category: 'PAINT', size: '4 Litre', cost: 566.4, selling: 720, unit: 'Bucket', brand: 'Smart' },
      { id: 'paint_prm_sme_10', name: 'Smart Exterior Primer', category: 'PAINT', size: '10 Litre', cost: 1170, selling: 1470, unit: 'Bucket', brand: 'Smart' },
      { id: 'paint_prm_sme_20', name: 'Smart Exterior Primer', category: 'PAINT', size: '20 Litre', cost: 2153.44, selling: 2670, unit: 'Bucket', brand: 'Smart' },

      /* --- PRIMERS: PROMISE INT PRIMER --- */
      { id: 'paint_prm_pri_1', name: 'Promise Interior Primer', category: 'PAINT', size: '1 Litre', cost: 142.78, selling: 170, unit: 'Can', brand: 'Promise' },
      { id: 'paint_prm_pri_4', name: 'Promise Interior Primer', category: 'PAINT', size: '4 Litre', cost: 527.46, selling: 610, unit: 'Bucket', brand: 'Promise' },

      /* --- PRIMERS: PROMISE EXT PRIMER --- */
      { id: 'paint_prm_pre_1', name: 'Promise Exterior Primer', category: 'PAINT', size: '1 Litre', cost: 177, selling: 220, unit: 'Can', brand: 'Promise' },
      { id: 'paint_prm_pre_4', name: 'Promise Exterior Primer', category: 'PAINT', size: '4 Litre', cost: 660.8, selling: 710, unit: 'Bucket', brand: 'Promise' },
      { id: 'paint_prm_pre_10', name: 'Promise Exterior Primer', category: 'PAINT', size: '10 Litre', cost: 1578.84, selling: 2000, unit: 'Bucket', brand: 'Promise' },
      { id: 'paint_prm_pre_20', name: 'Promise Exterior Primer', category: 'PAINT', size: '20 Litre', cost: 3063.28, selling: 3500, unit: 'Bucket', brand: 'Promise' },

      /* --- METAL & WOOD PRIMERS --- */
      { id: 'paint_prm_met_500', name: 'Red Oxide Metal Primer', category: 'PAINT', size: '500 ml', cost: 127.44, selling: 140, unit: 'Dabba', brand: 'Red Oxide' },
      { id: 'paint_prm_met_1l', name: 'Red Oxide Metal Primer', category: 'PAINT', size: '1 Litre', cost: 241.9, selling: 270, unit: 'Dabba', brand: 'Red Oxide' },
      { id: 'paint_prm_wd_500', name: 'Wood Primer', category: 'PAINT', size: '500 ml', cost: 136, selling: 145, unit: 'Dabba', brand: 'Wood Primer' },
      { id: 'paint_prm_wd_1l', name: 'Wood Primer', category: 'PAINT', size: '1 Litre', cost: 253.7, selling: 270, unit: 'Dabba', brand: 'Wood Primer' },

      /* --- General Wall Putty & Accessories --- */
      { id: 'paint_putty_40', name: 'Wall Putty White 40Kg', category: 'PAINT', size: '40 Kg', cost: 720, selling: 820, unit: 'Bag', brand: 'JK/Birla' },
      { id: 'paint_roller_9', name: 'Paint Roller 9 Inch', category: 'PAINT', size: '9"', cost: 95, selling: 130, unit: 'Pcs', brand: 'Standard' },
      { id: 'paint_brush_3', name: 'Paint Brush 3 Inch', category: 'PAINT', size: '3"', cost: 35, selling: 50, unit: 'Pcs', brand: 'Tiger' }
    ];
